name: CI CD Pipeline Demo

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy all files to DEV
        shell: powershell
        run: |
          Copy-Item `
            -Path "$env:GITHUB_WORKSPACE\source\*" `
            -Destination "C:\Deployments\DEV\" `
            -Recurse `
            -Force

  deploy-prod:
    if: github.ref == 'refs/heads/master'
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy all files to PROD
        shell: powershell
        run: |
          Copy-Item `
            -Path "$env:GITHUB_WORKSPACE\source\*" `
            -Destination "C:\Deployments\PROD\" `
            -Recurse `
            -Force